default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: root  # a senha que você usou na instalação
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: loja_api_development
